#pragma once

static const char* g_FilelessScript =
    "Write-Host \"==============================================\" -ForegroundColor Cyan\n"
    "Write-Host \"     Fileless tool, By Loyal                  \" -ForegroundColor Cyan\n"
    "Write-Host \"==============================================\" -ForegroundColor Cyan\n"
    "Write-Host \"\"\n"
    "\n"
    "$reportPath = Join-Path $PSScriptRoot \"Fileless_Scan_Results.txt\"\n"
    "$timestamp  = Get-Date -Format \"yyyy-MM-dd HH:mm:ss\"\n"
    "\"Fileless tool, By Loyal Scan Report\" | Out-File -FilePath $reportPath -Encoding utf8\n"
    "\"Generated: $timestamp\" | Add-Content -Path $reportPath\n"
    "\"=====================================\" | Add-Content -Path $reportPath\n"
    "\"\" | Add-Content -Path $reportPath\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "Write-Host \"[*] Récupération de l'historique complet des commandes...\" -ForegroundColor Yellow\n"
    "\"[HISTORIQUE COMPLET DES COMMANDES]\" | Add-Content -Path $reportPath\n"
    "\"------------------------------------\" | Add-Content -Path $reportPath\n"
    "\n"
    "$AllCmds = @()\n"
    "\n"
    "\n"
    "$PsEvents = Get-WinEvent -FilterHashtable @{\n"
    "    LogName = 'Microsoft-Windows-PowerShell/Operational'\n"
    "    Id      = 4104\n"
    "} -MaxEvents 1000 -ErrorAction SilentlyContinue\n"
    "\n"
    "foreach ($ev in $PsEvents) {\n"
    "    $text = ($ev.Properties[2].Value -replace \"`r`n|`r|`n\", \" \").Trim()\n"
    "    \n"
    "    if ($text.Length -lt 5) { continue }\n"
    "    if ($text -eq '$global:?') { continue }\n"
    "    $preview = if ($text.Length -gt 300) { $text.Substring(0, 300) + \"...\" } else { $text }\n"
    "    $AllCmds += [PSCustomObject]@{\n"
    "        Date    = $ev.TimeCreated\n"
    "        Source  = \"PowerShell\"\n"
    "        Command = $preview\n"
    "    }\n"
    "}\n"
    "\n"
    "\n"
    "$CmdEvents = Get-WinEvent -FilterHashtable @{\n"
    "    LogName = 'Security'\n"
    "    Id      = 4688\n"
    "} -MaxEvents 1000 -ErrorAction SilentlyContinue\n"
    "\n"
    "foreach ($ev in $CmdEvents) {\n"
    "    $proc    = $ev.Properties[5].Value  \n"
    "    $cmdLine = $ev.Properties[8].Value  \n"
    "    if (-not $cmdLine -or $cmdLine.Length -lt 3) { continue }\n"
    "    \n"
    "    if ($proc -match 'svchost|csrss|wininit|smss|lsass|RuntimeBroker|SearchHost') { continue }\n"
    "    $AllCmds += [PSCustomObject]@{\n"
    "        Date    = $ev.TimeCreated\n"
    "        Source  = \"CMD/Process [$([System.IO.Path]::GetFileName($proc))]\"\n"
    "        Command = $cmdLine.Trim()\n"
    "    }\n"
    "}\n"
    "\n"
    "\n"
    "$AllCmds = $AllCmds | Sort-Object Date\n"
    "\n"
    "Write-Host \"[+] $($AllCmds.Count) commandes récupérées.\" -ForegroundColor Green\n"
    "\n"
    "foreach ($cmd in $AllCmds) {\n"
    "    $dateStr = $cmd.Date.ToString(\"yyyy-MM-dd HH:mm:ss\")\n"
    "    $line = \"[$dateStr] [$($cmd.Source)]`n  $($cmd.Command)\"\n"
    "    Write-Host \"[$dateStr] \" -NoNewline -ForegroundColor DarkGray\n"
    "    Write-Host \"[$($cmd.Source)] \" -NoNewline -ForegroundColor Yellow\n"
    "    Write-Host $cmd.Command\n"
    "    Add-Content -Path $reportPath -Value $line\n"
    "    Add-Content -Path $reportPath -Value \"\"\n"
    "}\n"
    "\n"
    "\"\" | Add-Content -Path $reportPath\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "Write-Host \"\"\n"
    "Write-Host \"[*] Analyse fileless en cours...\" -ForegroundColor Yellow\n"
    "\"\" | Add-Content -Path $reportPath\n"
    "\"[DETECTION FILELESS]\" | Add-Content -Path $reportPath\n"
    "\"--------------------\" | Add-Content -Path $reportPath\n"
    "\n"
    "$MaliciousPatterns = @(\n"
    "    [regex]'(?i)\\[System\\.Reflection\\.Assembly\\]::Load\\(',\n"
    "    [regex]'(?i)Invoke-Expression\\s*\\(\\s*\\[System\\.Text\\.Encoding\\]',\n"
    "    [regex]'(?i)\\[Convert\\]::FromBase64String',\n"
    "    [regex]'(?i)-EncodedCommand\\s+[A-Za-z0-9+/=]{20,}',\n"
    "    [regex]'(?i)IEX\\s*\\(\\s*New-Object\\s+Net\\.WebClient',\n"
    "    [regex]'(?i)\\(New-Object\\s+Net\\.WebClient\\)\\.DownloadString',\n"
    "    [regex]'(?i)\\(New-Object\\s+Net\\.WebClient\\)\\.DownloadData',\n"
    "    [regex]'(?i)VirtualAlloc|VirtualAllocEx|CreateThread|WriteProcessMemory|OpenProcess',\n"
    "    [regex]'(?i)\\[Runtime\\.InteropServices\\.Marshal\\]::Copy',\n"
    "    [regex]'(?i)\\$shellcode\\s*=|0x90,0x90|msfvenom|meterpreter',\n"
    "    [regex]'(?i)amsiInitFailed|AmsiScanBuffer|amsiContext',\n"
    "    [regex]'(?i)DownloadString\\s*\\(\\s*[''\"]http',\n"
    "    [regex]'(?i)DownloadFile\\s*\\(\\s*[''\"]http.*\\.(exe|ps1|bat|dll|bin)',\n"
    "    [regex]'(?i)-nop\\s+-w\\s+hidden\\s+-enc',\n"
    "    [regex]'(?i)-windowstyle\\s+hidden\\s+.*-encodedcommand',\n"
    "    [regex]'(?i)schtasks.*\\/f.*cmd.*powershell.*-enc',\n"
    "    [regex]'(?i)regsvr32.*\\/i:http.*\\s+scrobj\\.dll',\n"
    "    [regex]'(?i)mshta\\s+http',\n"
    "    [regex]'(?i)rundll32.*\\bjavascript:',\n"
    "    [regex]'(?i)wmic.*process\\s+call\\s+create'\n"
    ")\n"
    "\n"
    "$Whitelist = @(\n"
    "    'Microsoft Visual Studio', 'vcpkg', 'cdxml', 'ROOT/StandardCimv2',\n"
    "    '$script:ClassName', 'ParameterSetName', 'FetchContent',\n"
    "    'bootstrap-vcpkg', 'VCPKG_ROOT', 'ModuleDefinition', 'CimCmdlets',\n"
    "    'Microsoft.PowerShell', 'WindowsPowerShell\\Modules',\n"
    "    'Program Files\\Microsoft', 'spdlog', 'imgui', 'antigravity'\n"
    ")\n"
    "\n"
    "$SuspiciousCount = 0\n"
    "$Seen = @{}\n"
    "\n"
    "\n"
    "foreach ($cmd in $AllCmds) {\n"
    "    $text = $cmd.Command\n"
    "    if (-not $text -or $text.Length -lt 5) { continue }\n"
    "\n"
    "    $isWhitelisted = $false\n"
    "    foreach ($w in $Whitelist) {\n"
    "        if ($text -match [regex]::Escape($w)) { $isWhitelisted = $true; break }\n"
    "    }\n"
    "    if ($isWhitelisted) { continue }\n"
    "\n"
    "    $cleanText = $text -replace '\\^', ''\n"
    "\n"
    "    $reasons = @()\n"
    "    foreach ($pat in $MaliciousPatterns) {\n"
    "        if ($cleanText -match $pat) { $reasons += \"[-] Pattern : $($pat.ToString())\" }\n"
    "    }\n"
    "    if ($reasons.Count -eq 0) { continue }\n"
    "\n"
    "    $hashKey = $text.Substring(0, [Math]::Min(200, $text.Length))\n"
    "    if ($Seen.ContainsKey($hashKey)) { continue }\n"
    "    $Seen[$hashKey] = $true\n"
    "\n"
    "    $SuspiciousCount++\n"
    "    $dateStr = $cmd.Date.ToString(\"yyyy-MM-dd HH:mm:ss\")\n"
    "    $source  = $cmd.Source\n"
    "    $header = \"`n[#] Suspicious Command $SuspiciousCount - $dateStr [$source]\"\n"
    "    Write-Host $header -ForegroundColor Red\n"
    "    Add-Content -Path $reportPath -Value $header\n"
    "\n"
    "    $preview = if ($text.Length -gt 300) { $text.Substring(0, 300) + \"...\" } else { $text }\n"
    "    Write-Host $preview\n"
    "    Add-Content -Path $reportPath -Value $preview\n"
    "    Write-Host \"    Reasons:\" -ForegroundColor Gray\n"
    "    Add-Content -Path $reportPath -Value \"    Reasons:\"\n"
    "    foreach ($r in $reasons) {\n"
    "        Write-Host \"      $r\" -ForegroundColor Gray\n"
    "        Add-Content -Path $reportPath -Value \"      $r\"\n"
    "    }\n"
    "}\n"
    "\n"
    "Write-Host \"\"\n"
    "if ($SuspiciousCount -eq 0) {\n"
    "    Write-Host \"[+] Aucune execution fileless suspecte détectée.\" -ForegroundColor Green\n"
    "    Add-Content -Path $reportPath -Value \"`n[+] Aucune execution fileless suspecte détectée.\"\n"
    "} else {\n"
    "    Write-Host \"[!] $SuspiciousCount commandes fileless suspectes trouvées.\" -ForegroundColor Red\n"
    "    Add-Content -Path $reportPath -Value \"`n[!] $SuspiciousCount commandes fileless suspectes trouvées.\"\n"
    "}\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "Write-Host \"\"\n"
    "Write-Host \"Do you want to analyze RAM to detect PE injection / shellcode? (Y/N): \" -NoNewline -ForegroundColor Cyan\n"
    "$analyzeRam = Read-Host\n"
    "\n"
    "if ($analyzeRam -match \"^[Yy]\") {\n"
    "    Write-Host \"`n[*] Loading Win32 memory API...\" -ForegroundColor Cyan\n"
    "\n"
    "    $MemAPI = Add-Type -PassThru -TypeDefinition @\"\n"
    "using System;\n"
    "using System.Runtime.InteropServices;\n"
    "\n"
    "public class MemAPI {\n"
    "    [StructLayout(LayoutKind.Sequential)]\n"
    "    public struct MEMORY_BASIC_INFORMATION {\n"
    "        public IntPtr BaseAddress;\n"
    "        public IntPtr AllocationBase;\n"
    "        public uint   AllocationProtect;\n"
    "        public IntPtr RegionSize;\n"
    "        public uint   State;\n"
    "        public uint   Protect;\n"
    "        public uint   Type;\n"
    "    }\n"
    "\n"
    "    [DllImport(\"kernel32.dll\")] public static extern IntPtr OpenProcess(uint dwDesiredAccess, bool bInheritHandle, int dwProcessId);\n"
    "    [DllImport(\"kernel32.dll\")] public static extern bool CloseHandle(IntPtr hObject);\n"
    "    [DllImport(\"kernel32.dll\")] public static extern int VirtualQueryEx(IntPtr hProcess, IntPtr lpAddress, out MEMORY_BASIC_INFORMATION lpBuffer, uint dwLength);\n"
    "    [DllImport(\"kernel32.dll\")] public static extern bool ReadProcessMemory(IntPtr hProcess, IntPtr lpBaseAddress, byte[] lpBuffer, int nSize, out int lpNumberOfBytesRead);\n"
    "}\n"
    "\"@\n"
    "\n"
    "    $PROCESS_VM_READ     = 0x0010\n"
    "    $PROCESS_QUERY_INFO  = 0x0400\n"
    "    $MEM_COMMIT          = 0x1000\n"
    "    $MEM_PRIVATE         = 0x20000\n"
    "    $PAGE_EXECUTE            = 0x10\n"
    "    $PAGE_EXECUTE_READ       = 0x20\n"
    "    $PAGE_EXECUTE_READWRITE  = 0x40\n"
    "    $PAGE_EXECUTE_WRITECOPY  = 0x80\n"
    "\n"
    "    $execProtections = @($PAGE_EXECUTE, $PAGE_EXECUTE_READ, $PAGE_EXECUTE_READWRITE, $PAGE_EXECUTE_WRITECOPY)\n"
    "\n"
    "    $selfPid = $PID\n"
    "    $processes = Get-Process | Where-Object { $_.Id -ne $selfPid -and $_.Id -ne 0 -and $_.Id -ne 4 }\n"
    "\n"
    "    Write-Host \"[*] Scanning $($processes.Count) processes for unbacked executable memory...\" -ForegroundColor Yellow\n"
    "    \"\" | Add-Content -Path $reportPath\n"
    "    \"[RAM MEMORY SCAN]\" | Add-Content -Path $reportPath\n"
    "    \"------------------\" | Add-Content -Path $reportPath\n"
    "\n"
    "    $findingsCount = 0\n"
    "\n"
    "    foreach ($proc in $processes) {\n"
    "        $hProcess = [MemAPI]::OpenProcess($PROCESS_VM_READ -bor $PROCESS_QUERY_INFO, $false, $proc.Id)\n"
    "        if ($hProcess -eq [IntPtr]::Zero) { continue }\n"
    "\n"
    "        $address = [IntPtr]::Zero\n"
    "        $mbi = New-Object MemAPI+MEMORY_BASIC_INFORMATION\n"
    "        $mbiSize = [Runtime.InteropServices.Marshal]::SizeOf($mbi)\n"
    "\n"
    "        while ([MemAPI]::VirtualQueryEx($hProcess, $address, [ref]$mbi, [uint32]$mbiSize) -ne 0) {\n"
    "            $isCommitted = ($mbi.State -eq $MEM_COMMIT)\n"
    "            $isPrivate   = ($mbi.Type -eq $MEM_PRIVATE)\n"
    "            $isExec      = $execProtections -contains $mbi.Protect\n"
    "\n"
    "            if ($isCommitted -and $isPrivate -and $isExec) {\n"
    "                $isMZ    = $false\n"
    "                $isRWX   = ($mbi.Protect -eq $PAGE_EXECUTE_READWRITE)\n"
    "                $readBuf = New-Object byte[] 2\n"
    "                $bytesRead = 0\n"
    "                if ([MemAPI]::ReadProcessMemory($hProcess, $mbi.BaseAddress, $readBuf, 2, [ref]$bytesRead)) {\n"
    "                    if ($bytesRead -ge 2 -and $readBuf[0] -eq 0x4D -and $readBuf[1] -eq 0x5A) {\n"
    "                        $isMZ = $true\n"
    "                    }\n"
    "                }\n"
    "\n"
    "                if ($isMZ -or $isRWX) {\n"
    "                    $findingsCount++\n"
    "                    $addrHex  = \"0x{0:X}\" -f $mbi.BaseAddress.ToInt64()\n"
    "                    $sizeKB   = [math]::Round($mbi.RegionSize.ToInt64() / 1KB, 1)\n"
    "                    $protName = switch ($mbi.Protect) {\n"
    "                        0x10 { \"PAGE_EXECUTE\" }\n"
    "                        0x20 { \"PAGE_EXECUTE_READ\" }\n"
    "                        0x40 { \"PAGE_EXECUTE_READWRITE (RWX)\" }\n"
    "                        0x80 { \"PAGE_EXECUTE_WRITECOPY\" }\n"
    "                        default { \"0x{0:X}\" -f $mbi.Protect }\n"
    "                    }\n"
    "                    $finding = if ($isMZ) { \"PE INJECTION DETECTED (MZ header in unbacked memory)\" } else { \"Suspicious RWX region (possible shellcode / JIT)\" }\n"
    "                    $line = \"[!] $finding`n    Process : $($proc.ProcessName) (PID $($proc.Id))`n    Address : $addrHex`n    Size    : $sizeKB KB`n    Protect : $protName\"\n"
    "                    Write-Host $line -ForegroundColor Red\n"
    "                    Add-Content -Path $reportPath -Value $line\n"
    "                    Add-Content -Path $reportPath -Value \"\"\n"
    "                }\n"
    "            }\n"
    "\n"
    "            try {\n"
    "                $next = $mbi.BaseAddress.ToInt64() + $mbi.RegionSize.ToInt64()\n"
    "                $address = [IntPtr]$next\n"
    "            } catch { break }\n"
    "            if ($address.ToInt64() -le 0) { break }\n"
    "        }\n"
    "\n"
    "        [MemAPI]::CloseHandle($hProcess) | Out-Null\n"
    "    }\n"
    "\n"
    "    if ($findingsCount -eq 0) {\n"
    "        Write-Host \"[+] Memory scan complete. No PE injection or shellcode detected.\" -ForegroundColor Green\n"
    "        Add-Content -Path $reportPath -Value \"[+] Memory scan complete. No PE injection or shellcode detected.\"\n"
    "    } else {\n"
    "        Write-Host \"`n[!] $findingsCount suspicious memory region(s) found. See report for details.\" -ForegroundColor Red\n"
    "        Add-Content -Path $reportPath -Value \"[!] $findingsCount suspicious memory region(s) found.\"\n"
    "    }\n"
    "} else {\n"
    "    Write-Host \"[*] RAM analysis skipped.\"\n"
    "    Add-Content -Path $reportPath -Value \"`n[*] RAM analysis skipped.\"\n"
    "}\n"
    "\n"
    "Write-Host \"`n==============================================\" -ForegroundColor Cyan\n"
    "Write-Host \"[+] Les résultats ont été sauvegardés dans :\" -ForegroundColor Green\n"
    "Write-Host \"    $reportPath\" -ForegroundColor White\n"
    "Write-Host \"==============================================`n\" -ForegroundColor Cyan\n"
    "\n"
    "Write-Host \"Press any key to exit...\"\n"
    "$Host.UI.RawUI.ReadKey(\"NoEcho,IncludeKeyDown\") | Out-Null\n";

static const char* g_USNCheckScript =
    "\n"
    "\n"
    "\n"
    "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8\n"
    "\n"
    "Write-Host \"[?] Checking USN Journal at path: C:\\`$Extend\\`$UsnJrnl:`$J\"\n"
    "\n"
    "\n"
    "try {\n"
    "    $bootTime = (Get-CimInstance Win32_OperatingSystem).LastBootUpTime\n"
    "} catch {\n"
    "    Write-Host \"[-] Failed to retrieve boot time.\" -ForegroundColor Red\n"
    "    \n"
    "    $uptimeMs = [Environment]::TickCount64\n"
    "    $bootTime = (Get-Date).AddMilliseconds(-$uptimeMs)\n"
    "}\n"
    "\n"
    "\n"
    "try {\n"
    "    \n"
    "    $fsutil = fsutil usn queryjournal C: 2>$null\n"
    "    if ($LASTEXITCODE -ne 0) {\n"
    "        Write-Host \"[-] Failed to query USN Journal. Ensure you are running as Administrator.\" -ForegroundColor Red\n"
    "    } else {\n"
    "        $firstLine = $fsutil | Select-Object -First 1\n"
    "        if ($firstLine -match '0x([0-9a-fA-F]{16})') {\n"
    "            $hexId = $Matches[1]\n"
    "            $decId = [Convert]::ToUInt64($hexId, 16)\n"
    "            $usnCreationTime = [datetime]::FromFileTime($decId)\n"
    "            \n"
    "            $usnStr = $usnCreationTime.ToString('yyyy-MM-dd HH:mm:ss')\n"
    "            $bootStr = $bootTime.ToString('yyyy-MM-dd HH:mm:ss')\n"
    "            \n"
    "            Write-Host \"[!] USN Journal creation time: $usnStr\"\n"
    "            Write-Host \"[#] System boot time: $bootStr\"\n"
    "            Write-Host \"\"\n"
    "            \n"
    "            if ($usnCreationTime -le $bootTime) {\n"
    "                Write-Host \"[#] The USN Journal is Intact!\" -ForegroundColor Green\n"
    "                Write-Host \"   Explanation: The USN Journal creation time ($usnStr) is BEFORE the boot time ($bootStr), indicating no recent changes or deletions.\"\n"
    "            } else {\n"
    "                Write-Host \"[!] `$UsnJrnl:`$J Suspicious!\" -ForegroundColor Red\n"
    "                Write-Host \"   Explanation: The USN Journal creation time ($usnStr) is AFTER the boot time ($bootStr), indicating it was recreated recently. This is highly suspicious.\"\n"
    "            }\n"
    "        } else {\n"
    "            Write-Host \"[-] Failed to retrieve USN Journal ID from fsutil output.\" -ForegroundColor Red\n"
    "        }\n"
    "    }\n"
    "} catch {\n"
    "    Write-Host \"[-] Error: $_\" -ForegroundColor Red\n"
    "}\n"
    "\n"
    "Write-Host \"\"\n"
    "\n"
    "if ($host.Name -eq \"ConsoleHost\") {\n"
    "    Write-Host \"Appuyez sur n'importe quelle touche pour fermer...\"\n"
    "    [void]$Host.UI.RawUI.ReadKey(\"NoEcho,IncludeKeyDown\")\n"
    "} else {\n"
    "    Read-Host \"Appuyez sur Entree pour fermer...\"\n"
    "}\n";
